version: '3.4'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  web:
    image: nginx
    volumes:
       - ./config/proxy:/etc/nginx/conf.d
       - ./config/proxy/web.conf:/etc/nginx/nginx.conf:ro
    links:
      - identifier:identifier
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  frontend:
    image: lblod/frontend-contact-hub:0.2.0
    labels:
      - "logging=true"
    environment: 
     EMBER_OAUTH_API_REDIRECT_URL: "https://organisaties.abb.lblod.info/authorization/callback"
     EMBER_OAUTH_API_KEY: "677af572-2e2f-4e61-ad38-036723bb314c"
     EMBER_OAUTH_API_BASE_URL: "https://authenticatie-ti.vlaanderen.be/op/v1/auth"
     EMBER_OAUTH_API_LOGOUT_URL: "https://authenticatie-ti.vlaanderen.be/op/v1/logout"
     EMBER_OAUTH_API_SCOPE: "openid vo profile abb_organisatieportaal"
    restart: always
