version: '3.4'

services:
  identifier:
    restart: "no"
  dispatcher:
    restart: "no"
  triplestore:
    ports:
      - "8890:8890"
    restart: "no"
  db:
    restart: "no"
  migrations:
    restart: "no"
  resource:
    restart: "no"
  cache:
    restart: "no"
  kalliope-api:
    restart: "no"
  deltanotifier:
    restart: "no"
  mocklogin:
    image: lblod/mock-login-service:latest
    links:
      - db:database
  sink:
    restart: "no"
  login:
    restart: "no"
  web:
    ports:
      - "80:80"
    restart: "no"
  frontend:
    restart: "no"
  uri-info:
    restart: "no"
