version: '3.4'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  identifier:
    image: semtech/mu-identifier:1.9.1
    environment:
      DEFAULT_ACCESS_CONTROL_ALLOW_ORIGIN_HEADER: "*"
      DEFAULT_MU_AUTH_ALLOWED_GROUPS_HEADER: "[{\"variables\":[],\"name\":\"public\"}]"
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  web:
    image: nginx
    volumes:
       - ./config/proxy:/etc/nginx/conf.d
       - ./config/proxy/web.conf:/etc/nginx/nginx.conf:ro
    links:
      - identifier:identifier
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  dispatcher:
    image: semtech/mu-dispatcher:latest
    volumes:
      - ./config/dispatcher:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  triplestore:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
      - ./config/db/virtuoso.ini:/data/virtuoso.ini
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  db:
    image: semtech/mu-authorization:0.6.0-beta.7
    environment:
      MU_SPARQL_ENDPOINT: "http://triplestore:8890/sparql"
      LOG_OUTGOING_SPARQL_QUERIES: "true"
      LOG_INCOMING_SPARQL_QUERIES: "true"
      LOG_ACCESS_RIGHTS: "true"
    volumes:
      - ./config/authorization:/config
  migrations:
    image: semtech/mu-migrations-service:0.7.0
    links:
      - triplestore:database
    volumes:
      - ./config/migrations:/data/migrations
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  # Ember-Metis
  uri-info:
    image: redpencil/mu-uri-info-service:0.2.1
    links:
      - db:database
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  resource-labels-cache:
    image: semtech/mu-cache:2.0.1
    links:
      - resource-labels:backend
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  resource-labels:
    image: lblod/resource-label-service:0.3.1
    links:
      - db:database
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"

  frontend:
    image: lblod/frontend-contact-hub
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
