version: '3.4'

services:
  identifier:
    ports:
      - "80:80"
    restart: "no"
  dispatcher:
    restart: "no"
  triplestore:
    ports: 
      - "8890:8890"
    restart: "no"
  db:
    restart: "no"
  migrations:
    restart: "no"
  resource:
    restart: "no"
  cache:
    restart: "no"
  uri-info:
    restart: "no"
  resource-labels-cache:
    restart: "no"
  resource-labels:
    restart: "no"
  kalliope-api:
    restart: "no"
  deltanotifier:
    restart: "no"
  mocklogin:
    image: lblod/mock-login-service:latest
    links:
      - db:database
  sink:
    restart: "no"
  login:
    restart: "no"
  frontend:
    image: lblod/frontend-contact-hub:latest
    labels:
      - "logging=true"
    restart: always
    environment: 
     EMBER_OAUTH_API_REDIRECT_URL: "https://organisaties.abb.lblod.info/authorization/callback"
     EMBER_OAUTH_API_KEY: "677af572-2e2f-4e61-ad38-036723bb314c"
     EMBER_OAUTH_API_BASE_URL: "https://authenticatie-ti.vlaanderen.be/op/v1/auth"
     EMBER_OAUTH_API_LOGOUT_URL: "https://authenticatie-ti.vlaanderen.be/op/v1/logout"
     EMBER_OAUTH_API_SCOPE: "openid vo profile abb_organisatieportaal"
    restart: always
  proxy:
    image: nginx:1.13
    volumes:
      - ./config/proxy-https:/etc/nginx/conf.d
    ports:
      - "443:443"