version: "3.4"

services:
  identifier:
    restart: "no"
    ports:
      - "80:80"
  dispatcher:
    restart: "no"
  triplestore:
    ports:
      - "8890:8890"
    restart: "no"
  db:
    restart: "no"
  migrations:
    volumes:
      - ./config/dev-migrations:/data/migrations/dev/
    restart: "no"
  migrations-triggering-indexing:
    restart: "no"
  resource:
    restart: "no"
  cache:
    restart: "no"
  kalliope-api:
    environment:
      SPRING_SECURITY_CONFIG: "/config/security-dev.yml"
    restart: "no"
  deltanotifier:
    environment:
      DEBUG_DELTA_SEND: "true"
      DEBUG_DELTA_NOT_SENDING_EMPTY: "true"
      DEBUG_DELTA_MATCH: "true"
      DEBUG_TRIPLE_MATCHES_SPEC: "true"
      DEBUG_DELTA_FOLD: "true"
    restart: "no"
  mocklogin:
    image: lblod/mock-login-service:latest
    links:
      - db:database
    restart: "no"
  sink:
    restart: "no"
  login:
    restart: "no"
  accountdetail:
    restart: "no"
  privacy-unit:
    restart: "no"
  privacy-worship:
    restart: "no"
  adressenregister:
    restart: "no"
  frontend:
    image: lblod/frontend-organization-portal:latest
    restart: "no"
  uri-info:
    restart: "no"
  delta-producer-background-jobs-initiator:
  # delta-producer-bg-jobs-initiator-organizations:
    ports:
      - 9999:80
    restart: "no"
  delta-producer-publication-graph-maintainer:
    build: ../delta-producer-publication-graph-maintainer
    environment:
      NODE_ENV: "development"
    ports:
      - 9229:9229
    restart: "no"
  search:
    restart: "no"
    volumes:
      - ./config/search/dev:/config
  elasticsearch:
    restart: "no"
  file:
    restart: "no"
  publication-triplestore:
    restart: "no"
    ports:
      - "8891:8890"
  delta-producer-dump-file-publisher:
    restart: "no"
  organizations-sync-with-sharepoint-jobs-initiator:
    # entrypoint: ["echo", "service disabled"]
    restart: "no"
  organizations-sync-with-sharepoint:
    # entrypoint: ["echo", "service disabled"]
    restart: "no"
  construct-administrative-unit-relationships:
    restart: "no"
  # delta-producer-pub-graph-maintainer-worship-posts:
  #   entrypoint: ["echo", "service disabled"]
  #   restart: "no"
  # delta-producer-pub-graph-maintainer-public:
  #   entrypoint: ["echo", "service disabled"]
  #   restart: "no"
  mandatarissen-consumer:
    entrypoint: ["echo", "service disabled"]
    restart: "no"
  leidinggevenden-consumer:
    entrypoint: ["echo", "service disabled"]
    restart: "no"
  worship-services-sensitive-consumer:
    entrypoint: ["echo", "service disabled"]
    restart: "no"
  ldes-backend:
    entrypoint: ["echo", "service disabled"]
    environment:
      BASE_URL: "http://localhost/ldes/"
  kbo-data-sync:
    restart: "no"
  # use this to test acmidm
  # tlsproxy:
  #   image: caddy:2
  #   restart: "no"
  #   ports:
  #     - "443:443"
  #   environment:
  #     OP_ADDRESS: "organisaties.abb.lblod.info"
  #   volumes:
  #     - ./config/tlsproxy-mock/Caddyfile:/etc/caddy/Caddyfile
