version: '3.4'

services:
  identifier:    
    ports:
      - "80:80"
    restart: "no"
  dispatcher:
    restart: "no"
  triplestore:
    ports: 
      - "8890:8890"
    restart: "no"
  db:
    restart: "no"
  migrations:
    restart: "no"
  resource:
    restart: "no"
  cache:
    restart: "no"
  kalliope-api:
    profiles:
      - disable-in-dev
    restart: "no"
  deltanotifier:
    profiles:
      - disable-in-dev
    restart: "no"
  sink:
    profiles:
      - disable-in-dev
    restart: "no"
  login:
    profiles:
      - disable-in-dev
    restart: "no"
  web:
    profiles:
      - disable-in-dev
    restart: "no"
  frontend:
    profiles:
      - disable-in-dev
    restart: "no"
  mocklogin:
    image: lblod/mock-login-service:latest
    links:
      - db:database