version: '3.4'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  web:
    image: nginx
    volumes:
       - ./config/proxy:/etc/nginx/conf.d
       - ./config/proxy/web.conf:/etc/nginx/nginx.conf:ro
    links:
      - identifier:identifier
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  frontend:
    image: lblod/frontend-contact-hub:0.2.0
    labels:
      - "logging=true"
    environment: 
     OAUTH_REDIRECT_URL: "https://contact-hub.lblod.info/authorization/callback"
     OAUTH_SWITCH_URL: "https://contact-hub.lblod.info/switch-login"
     OAUTH_API_KEY: "677af572-2e2f-4e61-ad38-036723bb314c"
     OAUTH_BASE_URL: "https://authenticatie-ti.vlaanderen.be/op/v1/auth"
     OAUTH_LOGOUT_URL: "https://authenticatie-ti.vlaanderen.be/op/v1/logout"
     OAUTH_SCOPE: "openid vo profile abb_organisatieportaal"
    restart: always
    logging: *default-logging
