application:
  security:
    enabled: true
    source: /config/source.json
    output: /config/out.json
    allowedIpAddresses: []
#server:
  #forward-headers-strategy: NATIVE
  #tomcat:
   # remote-ip-header: x-real-ip
