steps:
  build-feature:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: ${CI_REPO}
      tags: "improvement-${CI_COMMIT_BRANCH##improvement/}"
    secrets: [ docker_username, docker_password ]
when:
  branch: improvement/api-expansion*
  event: push